const Models = [
  // 'thenlper/gte-large',
  'Xenova/all-MiniLM-L12-v2',
  'Xenova/bge-large-en',
  'Xenova/gte-base',
  'Xenova/e5-large-v2',
  'Xenova/bge-small-en',
  'Xenova/instructor-xl',
  'Xenova/instructor-large',
  'Xenova/e5-base-v2',
  'Xenova/multilingual-e5-large',
  'Xenova/e5-large',
  'Xenova/gte-small',
  'Xenova/text-embedding-ada-002',
  'Xenova/e5-base',
  'Xenova/e5-small-v2',
  'Xenova/instructor-base',
  'Xenova/sentence-t5-xxl',
  'Xenova/multilingual-e5-base',
  'Xenova/XLM-3B5-embedding',
  'Xenova/gtr-t5-xxl',
  'Xenova/SGPT-5.8B-weightedmean-msmarco-specb-bitfit',
  'Xenova/e5-small',
  'Xenova/gtr-t5-xl',
  'Xenova/gtr-t5-large',
  'Xenova/XLM-0B6-embedding',
  'Xenova/multilingual-e5-small',
  'Xenova/sentence-t5-xl',
  'Xenova/all-mpnet-base-v2',
  'Xenova/sgpt-bloom-7b1-msmarco',
  'Xenova/jina-embedding-l-en-v1',
  'Xenova/SGPT-2.7B-weightedmean-msmarco-specb-bitfit',
  'Xenova/sentence-t5-large',
  'Xenova/MegatronBert-1B3-embedding',
  'Xenova/all-MiniLM-L6-v2',
  'Xenova/jina-embedding-b-en-v1',
  'Xenova/SGPT-1.3B-weightedmean-msmarco-specb-bitfit',
  'Xenova/gtr-t5-base',
  'Xenova/contriever-base-msmarco',
  // Add more models here if needed
];

export default Models;
